# Defining the constants

# Dimensions
SCREEN_WDTH = 500
SCREEN_HGHT = 700
SCREEN_MIDW = SCREEN_WDTH / 2
SCREEN_MIDH = SCREEN_HGHT / 2
SCREEN_SIZE = SCREEN_WDTH, SCREEN_HGHT

# Dimensions of game elements
BEAN_MSCW = SCREEN_MIDW - 25
BEAN_MSCH = SCREEN_MIDH - 60

FLAPPY_SIZE   = 350, 80
FINGER_SIZE   = 25, 25
TAP_SIZE      = 40, 25
GETREADY_SIZE = 200, 50
SHARE_SIZE    = 60, 40

DIGITS_SIDE = 20
DIGITS_SIZE = DIGITS_SIDE, DIGITS_SIDE

# Indent
FLAPPY_TOP = 100
FINGER_TOP = 450
SPACING = 10

SCORE_LEFT = 20
SCORE_TOP  = 20
